---
# handers file for Usability
 - name: Install oh-my-zsh
   command: "git clone -c core.autocrlf=input --depth=1 https://github.com/robbyrussell/oh-my-zsh.git .oh-my-zsh"
   notify: write zshrc

 - name: write zshrc
   copy:
     src: .zshrc 
     dest: ~/.zshrc
     mode: 'u=rw,go=r'
   notify: copy theme

 - name: copy theme
   copy:
     src: oxide.zsh-theme
     dest: ~/.oh-my-zsh/themes/oxide.zsh-theme
   notify: set shell to zsh

 - name: set shell to zsh
   user:
     name: root
     shell: /bin/zsh
     append: yes
