---
# tasks file for Usability
  - name: install toolchain
    apt:
      name: "{{ item }}"
      install_recommends: no
    with_items:
      - tmux
      - vim
      - git
      - tree
      - htop
  - name: install zsh 
    apt:
      name: zsh
      install_recommends: no
    notify: Install oh-my-zsh
